from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(784, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 0, 341, 61))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 40, 831, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 220, 801, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Melody1 = QtWidgets.QPushButton(self.centralwidget)
        self.Melody1.setGeometry(QtCore.QRect(-270, 240, 1091, 61))
        self.Melody1.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 260, 71, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(520, 370, 81, 81))
        self.start.setAutoDefault(False)
        self.start.setDefault(True)
        self.start.setFlat(False)
        self.start.setObjectName("pushButton_2")
        self.stop1 = QtWidgets.QPushButton(self.centralwidget)
        self.stop1.setGeometry(QtCore.QRect(190, 370, 81, 81))
        self.stop1.setCheckable(False)
        self.stop1.setAutoExclusive(True)
        self.stop1.setDefault(True)
        self.stop1.setObjectName("pushButton_3")
        self.hours = QtWidgets.QSpinBox(self.centralwidget)
        self.hours.setGeometry(QtCore.QRect(150, 120, 71, 31))
        self.hours.setObjectName("spinBox")
        self.mins = QtWidgets.QSpinBox(self.centralwidget)
        self.mins.setGeometry(QtCore.QRect(350, 120, 71, 31))
        self.mins.setObjectName("spinBox_2")
        self.sec = QtWidgets.QSpinBox(self.centralwidget)
        self.sec.setGeometry(QtCore.QRect(550, 120, 71, 31))
        self.sec.setObjectName("spinBox_3")
        self.label_h = QtWidgets.QLabel(self.centralwidget)
        self.label_h.setGeometry(QtCore.QRect(240, 130, 41, 16))
        self.label_h.setTextFormat(QtCore.Qt.AutoText)
        self.label_h.setObjectName("label_3")
        self.label_m = QtWidgets.QLabel(self.centralwidget)
        self.label_m.setGeometry(QtCore.QRect(440, 130, 41, 16))
        self.label_m.setTextFormat(QtCore.Qt.AutoText)
        self.label_m.setObjectName("label_4")
        self.label_s = QtWidgets.QLabel(self.centralwidget)
        self.label_s.setGeometry(QtCore.QRect(640, 130, 41, 16))
        self.label_s.setTextFormat(QtCore.Qt.AutoText)
        self.label_s.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 784, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Таймер"))
        self.Melody1.setText(_translate("MainWindow", "Мелодия1"))
        self.label_2.setText(_translate("MainWindow", "Рингтон"))
        self.start.setText(_translate("MainWindow", "Старт"))
        self.stop1.setText(_translate("MainWindow", "Отмена"))
        self.label_h.setText(_translate("MainWindow", "Ч"))
        self.label_m.setText(_translate("MainWindow", "МИН"))
        self.label_s.setText(_translate("MainWindow", "С"))

